/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InflationConverter {
        "moneyValue": number;
        "startDate": string;
    }
    interface LegalBanner {
        "bannerTitle": string;
        "policypageLink": string;
        "text": string;
        "type": "big" | "small" | "embedded";
    }
    interface SocialMediaWidget {
        "facebookLink": string;
        "twitterLink": string;
        "youtubeLink": string;
    }
    interface ToastAlert {
        "alertDescription": string;
        "alertTitle": string;
        "isActive": boolean;
    }
}
declare global {
    interface HTMLInflationConverterElement extends Components.InflationConverter, HTMLStencilElement {
    }
    var HTMLInflationConverterElement: {
        prototype: HTMLInflationConverterElement;
        new (): HTMLInflationConverterElement;
    };
    interface HTMLLegalBannerElement extends Components.LegalBanner, HTMLStencilElement {
    }
    var HTMLLegalBannerElement: {
        prototype: HTMLLegalBannerElement;
        new (): HTMLLegalBannerElement;
    };
    interface HTMLSocialMediaWidgetElement extends Components.SocialMediaWidget, HTMLStencilElement {
    }
    var HTMLSocialMediaWidgetElement: {
        prototype: HTMLSocialMediaWidgetElement;
        new (): HTMLSocialMediaWidgetElement;
    };
    interface HTMLToastAlertElement extends Components.ToastAlert, HTMLStencilElement {
    }
    var HTMLToastAlertElement: {
        prototype: HTMLToastAlertElement;
        new (): HTMLToastAlertElement;
    };
    interface HTMLElementTagNameMap {
        "inflation-converter": HTMLInflationConverterElement;
        "legal-banner": HTMLLegalBannerElement;
        "social-media-widget": HTMLSocialMediaWidgetElement;
        "toast-alert": HTMLToastAlertElement;
    }
}
declare namespace LocalJSX {
    interface InflationConverter {
        "moneyValue"?: number;
        "startDate"?: string;
    }
    interface LegalBanner {
        "bannerTitle"?: string;
        "policypageLink"?: string;
        "text"?: string;
        "type"?: "big" | "small" | "embedded";
    }
    interface SocialMediaWidget {
        "facebookLink"?: string;
        "twitterLink"?: string;
        "youtubeLink"?: string;
    }
    interface ToastAlert {
        "alertDescription"?: string;
        "alertTitle"?: string;
        "isActive"?: boolean;
    }
    interface IntrinsicElements {
        "inflation-converter": InflationConverter;
        "legal-banner": LegalBanner;
        "social-media-widget": SocialMediaWidget;
        "toast-alert": ToastAlert;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inflation-converter": LocalJSX.InflationConverter & JSXBase.HTMLAttributes<HTMLInflationConverterElement>;
            "legal-banner": LocalJSX.LegalBanner & JSXBase.HTMLAttributes<HTMLLegalBannerElement>;
            "social-media-widget": LocalJSX.SocialMediaWidget & JSXBase.HTMLAttributes<HTMLSocialMediaWidgetElement>;
            "toast-alert": LocalJSX.ToastAlert & JSXBase.HTMLAttributes<HTMLToastAlertElement>;
        }
    }
}
